# http://travis-ci.org/#!/ipython/ipython
language: python
python:
    - 2.7
    - 3.3
before_install:
    # workaround for https://github.com/travis-ci/travis-cookbooks/issues/155
    - sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm
    - easy_install -q pyzmq
    - pip install jinja2 sphinx pygments tornado requests
    # Pierre Carrier's PPA for PhantomJS and CasperJS
    - sudo add-apt-repository -y ppa:pcarrier/ppa
    - sudo apt-get update
    - sudo apt-get install pandoc casperjs
install:
    - python setup.py install -q 
script:
    - if [[ $TRAVIS_PYTHON_VERSION == '2.'* ]]; then cd /tmp; iptest; fi
    - if [[ $TRAVIS_PYTHON_VERSION == '3.'* ]]; then cd /tmp; iptest3; fi
